version: "3.7"
services:
  project-core:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
